### ISSUE TITLE
How to disable the "Prompt completion".

### ISSUE THREAD

**Issue by Scribilicious** [astoilkov/IntelliBar#1]
I didn't found the key combo to get to the Preferences page.

Cheers,

Jens

**Comment by astoilkov** [comment]
Hey @Scribilicious,

Preferences are up in the menu bar. You can disable from there:
![CleanShot 2023-04-13 at 14 50 02@2x](https://user-images.githubusercontent.com/884810/231749826-1e9f065d-0972-4724-9ee1-0cdf3039be14.png)

**Comment by astoilkov** [comment]
I will close this issue but let me know if that didn't work out for you.
