### ISSUE TITLE
No menubar?

### ISSUE THREAD

**Issue by tborychowski** [astoilkov/IntelliBar#3]
Hi,
I just upgraded to version 0.7.3 (Apple Silicon).
What happened?
No menubar icon anymore? (not to mention the nice looking star or something changed into the ugly asymmetrical cloud ;-P)

Is this a bug (no menubar icon and app only in the dock) or a feature?

**Comment by erusev** [comment]
Hi there, and thanks for reaching out!

> What happened?

The app used to live in the menu bar, and now it lives in the dock.

> Is this a bug (no menubar icon and app only in the dock) or a feature?

We see it as a feature that brings a number of benefits:

- You can cmd-tab to and out of it.
- You can use it side-by-side with other apps.
- You can control it with a window manager.
- You can more easily move it to another screen.
- You can use the menu bar to discover features and set custom shortcuts from macOS prefs.

It does add an extra item to your dock, but other than that, the we don't see much of a downside -- you can still launch the app with a global shortcut, and it's still a small window that you can easily hide when you no longer need it.

Do you have any specific concerns about the change? Ex: particular workflows that are now harder to do?

**Comment by tborychowski** [comment]
Hi,
Thanks for your response.
My workflow was simple: ask a question, get an answer. 
I want to use it similarly to alfred: keyboard shortcut - type, esc to get it out of the way.
I don't want yet another item to my dock, I don't want it to clutter my cmd+tab list, and I don't want to see it when I don't need it.


If I was on the other side, I'd rather consider adding an option (show in menubar/dock/both), as a lot of apps provide, rather than changing behaviour completely.
It could e.g. work like MacUpdater - it sits in the menubar, can show up on key stroke, and when it does - it becomes a regular window that you can move around and cmd+tab into. And when you close the window - it goes back to menubar.

But hey, it's your app, and your decision, and I understand completely. 
I also develop apps, and feel the pain of the impossible task of making everyone happy :-D

Anyways, there are plenty other apps like this, and I'm sure I'll find a replacement.

**Comment by erusev** [comment]
Thanks for sharing your thoughts on this!

> If I was on the other side, I'd rather consider adding an option (show in menubar/dock/both), as a lot of apps provide

Can you think of other apps that do this? We don't want to make the app too complicated, but if we find a simple way to do this, we will consider it.

**Comment by tborychowski** [comment]
Here are some:
- 1Password - sits in menubar, brings app a spotlight-like quick search when you press a global shortcut, and you can open the full window from the menubar icon
- Adguard for mac - sits in the menubar, you can open preferences in a regular window
- Alfred is the same - search box on shortcut, preferences open in a normal window
- Airbuddy - same as above
- [MacGTP](https://goodsnooze.gumroad.com/l/menugpt) app (that I'm currently using) has an option to either open a popup from the menubar, a spotlight-like search box or a normal window with the dock icon
- Parcell app (for delivery tracking) has a nice menubar popup, with an icon that brings a normal window

These are the ones I use regularly, but there's many more that I don't remember atm.
To me a regular window is justified if the app in question is the one you work with directly (like writing a doc in Word or writing code in vscode, or browsing), but to me a chat-gtp app is a sidekick app, a tool that I would use when doing something else, just like alfred, spotlight, 1password, a dictionary lookup, etc.
I can understand that some people would use it together with e.g. a word doc, to generate content, and it's probably a valid use-case. But mine also is, and I believe I'm not the only one using the app like that :-)

Let me know what you decide, Intellibar (in v0.6) was still the best out of the ones I tested.
I would be even happy using that version if didn't auto-update itself without asking me (that's another bad UX pattern btw. Always put user in control!)

**Comment by milescajus** [comment]
> I want to use it similarly to alfred: keyboard shortcut - type, esc to get it out of the way. I don't want yet another item to my dock, I don't want it to clutter my cmd+tab list, and I don't want to see it when I don't need it.
> 
> If I was on the other side, I'd rather consider adding an option (show in menubar/dock/both), as a lot of apps provide, rather than changing behaviour completely.

I know this issue has been closed, but while the re-introduction of a menu bar icon is a welcome update (and I've been able to approximate my old workflow by 'hiding' IntelliBar with ⌘Q or ⌘W to close the active window, thus removing the dock icon without disabling the global shortcut to bring it back), I would still strongly second the idea of an option in the settings to toggle between a dock icon and menu icon (or both, though I personally would choose only the menu icon).

P.S. I also much preferred the old star icon over the cloud (on the menu bar) since it was far more distinct and recognizable at a glance than the blob-shaped cloud. The cloud design used for the full app icon itself is admittedly quite nice though :)

**Comment by tborychowski** [comment]
@milescajus check out [Beam](https://getbeam.ai), it fits my workflow perfectly!

**Comment by erusev** [comment]
@milescajus Thanks for sharing your feedback on this. We are experimenting with a workflow that will let you use IntelliBar without a dock icon.

**Comment by erusev** [comment]
@milescajus 

A couple of questions:

- What if you have a follow-up question -- how should it work?
- What if you want ask a question, see the response, hit esc to go back to your app, but then realize you want to see the same response again -- how should this work?
